const master_mentors = [
	{
		path : "assets/css/images/Animesh.jpg",
		personTitle : "Animesh Joshi, WDM Valley (IA)",
		description : "Animesh Joshi is a senior at WDM Valley High School and has eight career bids, going to the Tournament of Champions three times. After working with PepTalk the last two years, he is looking forward to running the program as co-president and acting as web developer! He's championed the Yale Invitational, Florida Blue Key, and the Iowa State Tournament (in PF!), while also reaching elimination rounds at Bronx, Apple Valley, the Glebrooks, Blake, Lexington, and Harvard. His debate interests include analytical philosophy, theory, and the occasional trick. He's very excited to continue mentoring this year!",
		region : "Midwest",
	},
	{
		path : "assets/css/images/Evan.jpg",
		personTitle : "Evan Li, Lexington (MA)",
		description : "Evan is a senior at Lexington High School in Massachusetts, going into his 4th year of debate. After working with PepTalk last year, he is looking forward to running the program as a co-president! His debate interests include theory and identity Kritiks, but he is open to teaching all kinds of debate. Thus far, Evan has received 5 bids to the Tournament of Champions and has championed various tournaments, including the Newark Invitational, Harrison Round Robin, and Massachusetts State Tournament while also reaching elimination rounds of Harvard, Princeton, UPenn, and Mid American Cup. His teaching experience includes tutoring multiple students at his high school and working at various debate camps for middle schoolers.",
		region : "Northeast",
	},
	{
		path : "assets/css/images/Perry.jpg",
		personTitle : "Perry Beckett, American Heritage (FL)",
		description : "Perry is a senior at American Heritage in Plantation Florida who is in his fourth year of debate. After working with PepTalk last year, he is looking forward to helping run the program as vice president! He has reached multiple bid rounds at large national tournaments, and is the captain of his school’s LD team. Some of his debate interests include Tricks, Framework debate, and Theory.",
		region : "Southeast",
	},
	{
		path : "assets/css/images/Tajaih.png",
		personTitle : "Tajaih Robinson",
		description : "Tajaih Robinson is a rising senior at  Success Academy High School of Liberal Arts in New York. Tajaih has qualified to the TOC 3 times, getting to octos his junior year, as well as particpating in late outrounds at national circuit tournaments. He primarily specializes in kritikal debate.",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Abby.jpg",
		personTitle : "Abby Morris, Lake Highland (FL)",
		description : "Abby is a junior from Lake Highland Preparatory School. She has been debating for 4 years and this is her second year with Pep Talk. Abby has gotten 1 career bid thus far and has had 7 bid rounds. She was also top speaker at the Florida State Tournament. Abby enjoys K/High Theory debate the most but also reads a lot of theory and phil.",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Joanne.jpg",
		personTitle : "Joanne Park, Archbishop Mitty (CA)",
		description : "Joanne will be entering her senior year at Archbishop Mitty in California, and has competed on both her local and national circuits, frequently reaching elimination rounds. She has been her school's LD captain for two years and will be Team President in the fall. Her debate interests are mostly Ks and LARP, and she is excited to be a mentor for PepTalk this year!",
		region : "West",
	},
    {
		path : "assets/css/images/Tej.png",
		personTitle : "Tej Gedela, Enloe (NC)",
		description : "Tej is a senior at William G Enloe and has six career bids to the TOC. He is currently the captain of his school's LD team. He championed the Strake tournament as a junior, and has been in semis of Emory and Florida Blue Key as well as quarters of Glenbrooks. Tej has reached elims of multiple other bid tournaments and attended several round robins. His debate interests include policymaking arguments, theory, and some kritiks. He is excited to work with PepTalk this year!",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Avery.jpg",
		personTitle : "Avery Fortier, Lexington (MA)",
		description : "Avery is going into her fourth year debating for Lexington. She has consistently broken at national circuit tournaments and won several locals. Avery has been in three bid rounds and bid at Blake. Avery has also been selected as TA for her school’s novices this year and works as a mentor for WIN Debate. Her debate interests include high theory and critical positions. She is super excited to be a part of Pep Talk this year!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/John.jpg",
		personTitle : "John Choi, Loyola (CA)",
		description : "John Choi is currently a Senior at Loyola High School in Los Angeles- in his junior year he was first speaker at the UNLV tournament, broke to doubles at Valley, Octas at UNLV and quarters at Alta. John specializes in critical literature, LARPing, and theory. On the side, he enjoys photography and working out. John is excited to work with PepTalk and is available to answer any questions via Facebook or PepTalk!",
		region : "West",
	},
    {
		path : "assets/css/images/Serena.jpg",
		personTitle : "Serena Lyou, Lake Highland (FL)",
		description : "Serena Lyou is a senior at Lake Highland Preparatory School and has been debating on the national circuit since her freshman year. She is currently the LD novice team captain and enjoys working with novices and fellow teammates. She is excited to be a mentor for PepTalk to help debaters who don't have access to the same resources as others. Her debate interests include critical literature, specializing in identity politics her junior year.",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Andrew.png",
		personTitle : "Andrew Qin, Houston Memorial (TX)",
		description : "Andrew Qin is a senior at Memorial High School in Houston. As a junior, he won the University of Houston tournament, qualified to the TOC, and broke to octafinals of TFA State. Andrew specializes in theory but is familiar with philosophy, identity Kritiks, and some LARP.",
		region : "Texas",
	},
    {
		path : "assets/css/images/Lauren.jpg",
		personTitle : "Lauren Gilbert, WDM Valley (IA)",
		description : "Lauren Gilbert is a senior at Valley High School and has been debating for five years. Lauren serves as a mentor for W.in debate. Last year, she cleared at multiple bid tournaments and competed at the TOC. Her debate interests include framework and theory, and she is excited to be a mentor for PepTalk!",
		region : "Midwest",
	},
        {
		path : "assets/css/images/Zach1.jpg",
		personTitle : "Zach Lu, Needham (MA)",
		description : "Zachary Lu is a rising senior at Needham High School in Massachusetts. His debate interests include LARP debate, philosophy, and kritikal affirmatives, though he’s done every type of debate (except tricks). Thus far, he has received 2 bids to the TOC and has participated in the Harvard and Harrison Round Robins, semifinaling at the latter. Zachary has reached elimination rounds at Harvard, Emory, Apple Valley, Glenbrooks, and more, finaling at Princeton. He is his school’s LD captain, and is looking forward to mentoring with Peptalk!",
		region : "Northeast",
	},
        {
		path : "assets/css/images/Isabella.jpg",
		personTitle : "Isabella Nadel, WDM Valley (IA)",
		description : "Isabella Nadel is a senior at Valley High School and has been debating for four years. Last year, she competed at the TOC and has cleared at multiple bid tournaments. Isabella’s debate interests include framework and theory. This is her second year mentoring with W.in Debate and she is excited to begin working with PepTalk!",
		region : "Midwest",
	},
        {
		path : "assets/css/images/Meghana.jpg",
		personTitle : "Meghana Srinivasa, Lake Highland (FL)",
		description : "Meghana Srinivasa is a senior at Lake Highland Preparatory School and is the LD novice team captain. She enjoys working with her current novices and teammates, and she looks forward to mentoring debaters that do not have access to the same resources as larger programs. Her debate interests include theory and critical literature.",
		region : "Southeast",
	},
        {
		path : "assets/css/images/Ben1.png",
		personTitle : "Ben Waldman, Walt Whitman (MD)",
		description : "Ben is a rising junior at Walt Whitman High School in Bethesda, Maryland, where he will serve as an LD captain. He broke at Yale, Valley, Bronx, Glenbrooks, Princeton, and Harvard his sophomore year, bidding at Yale and Bronx. His debate interests include moral philosophy, high theory, and LARP. He’s excited to be working with PepTalk this year!",
		region : "Northeast",
	},
        {
		path : "assets/css/images/Rohan.png",
		personTitle : "Rohan Rao, Seven Lakes (TX)",
		description : "Rohan Rao is a rising senior at Seven Lakes High School in Texas. During his debate career, he has broken at the Texas Forensics Association State Tournament twice (reaching double-octos as a sophomore and octo-finals as a junior). He competes on the national circuit, clearing to elimination rounds at the Strake Jesuit Invitational, the University of Texas Longhorn Classic, and the University of Houston Cougar Classic. His debate interests include theory and policy arguments.",
		region : "Texas",
	},
      {
		path : "assets/css/images/Mimi.jpg",
		personTitle : "Mimi Sawhney, Lake Highland (FL)",
		description : "Mimi Sawhney is a junior at Lake Highland Preparatory School and is in her 4th year of debate. She is captain of the novice team at her school and serves as a mentor for w.in debate. She enjoys working with younger teammates and looks forward to mentoring debaters throughout the year. Her debate interests include framework and theory.",
		region : "Southeast",
	},
      {
		path : "assets/css/images/Annie.jpg",
		personTitle : "Annie Wang, Bronx Science (NY)",
		description : "Annie Wang debated for Bronx Science in New York the past 3 years. Her debate interests includes: performance Ks surrounding Chinese American identity/feminism, high theory such as Deleuze and Lacan, and theory/topicality. She’s really exited to be paired up with a mentee and work with them the rest of the season!",
		region : "Northeast",
	},
      {
		path : "assets/css/images/Kevin.png",
		personTitle : "Kevin Yang, Lexington (MA)",
		description : "Kevin is a senior at Lexington High School entering his fourth year of debate. He's reached elimination rounds at Pennsbury and Blake as well as winning the MA state championship. His main debate interests are policy arguments (LARP) and theory, but he also enjoys reading critical arguments and some philosophies. Kevin looks forward to mentoring debaters!",
		region : "Northeast",
	},
      {
		path : "assets/css/images/Ava.jpg",
		personTitle : "Ava Zinman, Harrison (NY)",
		description : "Ava is a rising senior and Captain of her debate team at Harrison High School. She received 5 career bids to the TOC and reached finals of Columbia and Byram Hills, semis of Scarsdale and NCFL, quarters of Apple Valley and Newark, and octos of Greenhill, Glenbrooks, and Lexington. She has received speaker awards at Lexington, Columbia, Newark, Glenbrooks, Scarsdale, and Apple Valley, and has attended the Greenhill and Harvard Round Robins. Ava runs her middle school’s debate club and tutors students in debate both independently and through the W.in Debate program. Her interests include identity kritiks, traditional debate and LARP. She’s looking forward to mentoring for PepTalk this year!",
		region : "Northeast",
	},
      {
		path : "assets/css/images/Scott.jpg",
		personTitle : "Scott Klein, Hunter (NY)",
		description : "Scott Klein is entering his 4th year of LD debate as a rising senior at Hunter College High School in New York, where he will serve as team president. He qualified to the TOC his junior year and was an Octofinalist at the 2019 NCFL Grand National tournament. His debate interests include ethical framework, theory and critical debate. He was the LD novice director at his school and has volunteered at multiple urban debate league summer camps as an instructor. He was a mentor through the PepTalk program last year and is excited for the upcoming year!",
		region : "Northeast",
	},
      {
		path : "assets/css/images/Arun.jpg",
		personTitle : "Arun Mehra, Strake Jesuit (TX)",
		description : "Arun Mehra is going to be a senior at Strake Jesuit while entering his 4th year of debate. He has reached out rounds and bid rounds at major national tournaments such as the Harvard Invitational, Glenbrooks Tournaments, and the Mid America Cup. His debate interests include theory, Kantian framework, larp, critical literature including anti-blackness, settler colonialism, and high theory.",
		region : "Texas",
	},
      {
		path : "assets/css/images/Asher.png",
		personTitle : "Asher Towner, Crescenta Valley (CA)",
		description : "Asher is a senior at Crescenta Valley high school, has bid to the TOC 3x, reached finals of USC, semis of CPS, octos of HW, had 8 bid rounds, and got speaker awards at most of the tournaments they went to last year. Asher specializes in policy and theory styles of debate (they guess). Asher is looking forward to mentoring this year!",
		region : "West",
	},
      {
		path : "assets/css/images/Matthew.jpg",
		personTitle : "Matthew Liu, Acton-Boxborough (MA)",
		description : "Matthew is entering his fourth year of debate as a senior at Acton-Boxborough Regional High school, where he is one of the LD captains. His junior year, he qualified to the NCFL and NSDA national tournaments and bid to the TOC. He specializes in LARP and theory, and is excited to be working with PepTalk this year!",
		region : "Northeast",
	},
      {
		path : "assets/css/images/Elizabeth.jpg",
		personTitle : "Elizabeth Lee, Bergen (NJ) ",
		description : "Elizabeth is a senior at Bergen County Academies in New Jersey, where she is president of the national circuit debate team. Her debate interests include philosophy and critical literature. She's excited to work with mentees this year!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Angela.png",
		personTitle : "Angela Zhong, Cypress Woods (TX) ",
		description : "Angela Zhong is a senior at Cypress Woods high school and past member of the USA Debate Development Team. She is also the Debate Captain at her school and has placed in the top 10 at TFA and UIL state championships. Angela is excited to give back to the debate community as a mentor for W.in Debate and Peptalk. In her free time, she enjoys figure skating and reading the news.",
		region : "Texas",
	},
    {
		path : "assets/css/images/Ben.jpg",
		personTitle : "Ben Thomas, KAPS (TX) ",
		description : "Ben Thomas is a rising senior at KAPS school in Texas. She has been involved with debate for over 4 years beginning in a traditional circuit learning the basics of debate and moving up to the national circuit. Ben has received invites to the Strake Jesuit, Quarry Lane, and Greenhill round robins. In her first year of national circuit debate she received a bid to the TOC by championing the heritage hall tournament. Participating in 5 bid rounds last year. Notably was 5th speaker at greenhill, top speaker at heritage hall and 18th speaker at the tournament of champions. Ben specializes in reading embodied performance positions pertaining to transness.",
		region : "Texas",
	},
    {
		path : "assets/css/images/Nate.jpg",
		personTitle : "Nate Kruger, Hunter (NY) ",
		description : "Nate is a senior at Hunter College High School entering his fourth year of debate. He's reached elimination rounds at many national circuit tournaments, and has received invites to the UPenn, Harrison, and Byram Round Robins. His primary debate interests are philosophy and theory, though he is also enjoys reading kritikal positions and going for policy-making arguments. Nate is looking forward to mentoring this year!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Gabrielle.png",
		personTitle : "Gabrielle Lee, All Saints Episcopal School (TX)  ",
		description : "Gabby Lea is a rising senior from All Saints Episcopal School in Tyler, TX where they will be their team’s LD captain for the 2nd year in a row. They run mostly traditional philosophy and LARP arguments, but are familiar with every type of argument normally run in LD. They have won multiple locals, consistently cleared at bid tournaments such Harvard, Colleyville, and more, and qualified to the NSDA national tournament twice in a row. They are super excited to be a mentor with PepTalk this year.",
		region : "Texas",
	},
    {
		path : "assets/css/images/David.png",
		personTitle : "David Edwards, Charlotte Catholic (NC) ",
		description : "David is a rising senior at Charlotte Catholic and has five career bids to the TOC, making it to octofinals his junior year. He is currently the president of Charlotte Catholic’s speech and debate team and going into his fourth year in debate and third year in national circuit debate. His junior year, he championed the Durham Invitational and made it to octos of Apple Valley and Emory. David has broken to elims and bid rounds and earned speaker awards at several other tournaments. His main debate interests are policy and clash of civilizations debates. David can’t wait to work with PepTalk this season!",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Elizabeth.jpg",
		personTitle : "Elizabeth Lee, Bergen (NJ) ",
		description : "Elizabeth is a senior at Bergen County Academies in New Jersey, where she is president of the national circuit debate team. Her debate interests include philosophy and critical literature. She's excited to work with mentees this year!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Breigh.jpg",
		personTitle : "Breigh Platt, Frisco Legacy (TX)",
		description : "Breigh is a junior who debates for Frisco Legacy in Texas. She has cleared at multiple national tournaments, debating both in TX and the North East. Her debate interests are concentrated in high theory authors such as Baudrillard and Deleuze, theory, and non-T affs. She can't wait to work with Pep Talk!",
		region : "Texas",
	},
    {
		path : "assets/css/images/Josh.png",
		personTitle : "Josh Porter, Strake Jesuit (TX) ",
		description : "Joshua is a senior at Strake Jesuit College Preparatory, going into his 4th year of debate. His debate interests include identity Kritiks and philosophical arguments, but he is open to helping anyone get better at debate. He received 1 bid and at-larged to the Tournament of Champions, just barely missing the bar for reaching elimination rounds. His teaching experience includes teaching the basic of LD to dozens of students just starting debate.",
		region : "Texas",
	},
    {
		path : "assets/css/images/Arjun.png",
		personTitle : "Arjun Chopra, Blair Academy (NJ) ",
		description : "Arjun is a rising Junior and captain of the Blair Academy speech and debate team. They have consistently broken and received speaker awards at bid tournaments including the New York City Invitational, the Princeton Classic, the Ridge Invitational, the Newark Invitational, the Upenn Tournament, the Harvard Forensics Tournament, and was a finalist at the Woodward 2nd year National Championship. Arjun’s interests include high theory, performative, and identity based kritikal arguments, and they are looking forward to mentoring for PepTalk this year.",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Ben2.png",
		personTitle : "Ben Erdman, Strake Jesuit (TX) ",
		description : "Ben Erdmann is a junior at Strake Jesuit. In his sophomore year, Ben received 1 bid and reached 2 bid rounds. He also championed multiple local tournaments on the Houston circuit. His teaching experience includes helping to teach novices at Strake as well as working at multiple debate camps for middle-schoolers. His debate interests include kritikal literature and policy arguments. He’s excited to help out as a mentor for PepTalk this year!",
		region : "Texas",
	},
    {
		path : "assets/css/images/Anika.jpg",
		personTitle : "Anika Dham, American Heritage (FL) ",
		description : "Anika has debated for American Heritage school since she was a freshman and loves it. She joined peptalk to help out students who may not have had a strong support system like her. She enjoys theory, and philosophy debates.",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Lukas.jpg",
		personTitle : "Lukas Krause, Archbishop Mitty (CA) ",
		description : "Lukas is a Junior at Archbishop Mitty High School in their second year of LD Debate. Last year, they reached outrounds at multiple tournaments and earned a bid to the TOC. They also will serve as their school’s captain of Circuit LD Debate for the upcoming school year. They are interested in K, theory, and small plan/soft left affs as their primary debate arguments.",
		region : "West",
	},
    {
		path : "assets/css/images/Reetesh.png",
		personTitle : "Reetesh Sudhakar, Westview (OR) ",
		description : "Reetesh Sudhakar is a rising junior at Westview High School, in Portland, Oregon. In LD, he broke at UT Austin, University of Puget Sound, and the Harvard Invitational his sophomore year. His debate interests include philosophy, LARP, and theory debate. He is extremely excited to be a mentor with PepTalk this coming year!",
		region : "West",
	},
    {
		path : "assets/css/images/Jason.jpg",
		personTitle : "Jason Lan, Syosset (NY) ",
		description : "Jason Lan is a senior at Syosset High School in his third year of debate, currently serving as team captain. As a junior, he reached outrounds at Columbia and States, and coached/mentored multiple students to champion multiple JV and novice invitationals within the area. This, and working in NYC's UDL has given Jason the tools and motivation to teach younger students, and he's excited to join PepTalk this year.",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Michael.png",
		personTitle : "Michael Zhou, Cypress Ranch (TX)",
		description : "Michael is going to be a senior at Cypress Ranch HS. He has broken at several bid tournaments and earned a bid to the TOC. His debate interests focus on K’s, especially Agamben and Weheliye. He’s looking forward to mentoring through PepTalk",
		region : "Texas",
	},
     {
		path : "assets/css/images/Max.png",
		personTitle : "Max Tran, Lamar (TX)",
		description : "Max Tran is a rising senior at Lamar High School and is excited to work with incoming debaters to learn advocacy skills and explore literature bases. Coming from a background with little institutional support, he has reached the bid round at Churchill despite navigating barriers to even compete. Max already has experience working with his neighboring middle school team and wants to ensure everyone is able to access the education they deserve.",
		region : "Texas",
	},
     {
		path : "assets/css/images/Shreya.jpg",
		personTitle : "Shreya Mehta, Kinkaid (TX)",
		description : "Shreya Mehta is a fourth-year and senior in debate and LD captain at the Kinkaid School in Houston, Texas. She has participated in multiple national tournaments and reached outrounds at tournaments like Meadows, Grapevine, and University of Texas at Austin, and her debate interests include: high theory such as Deleuze and Lacan, theory/T, and gender/feminist literature. She has volunteered to mentor students in her school and serve through community organizations like Houston Urban Debate League. She is really excited to meet mentees and work with them throughout the season!",
		region : "Texas",
	},
     {
		path : "assets/css/images/Nikki.jpg",
		personTitle : "Nikita Tangaturi, American Heritage (FL)",
		description : "Nikita Tanguturi has been in debate for 6 years, debating at American Heritage Boca for the last 2 years, where she is currently a junior. She is the current president of the debate team, and was the event captain of ld last year. She has made it to the bubble round and broke at various toc bid tournaments, and broke at the Florida State tournament. As a debater she is primarily interested in kritikal debate, both identity based and postmodern. Her favorite authors include Baudrillard, Bataille, Freud, N’yongo, and Warren. She coaches younger students on her team as well as middle school students in her county and through w.in debate, and looks forward to mentoring for peptalk!",
		region : "Southeast",
	},
     {
		path : "assets/css/images/Jalyn.jpg",
		personTitle : "Jalyn Wu, WDM Valley (IA)",
		description : "Jalyn has debated for WDM Valley for 5 years, clearing and making bid rounds at multiple national circuit tournaments. Her favorite styles of debate are identity k/performance/, framework and edgy arguments. Jalyn has previously worked with the novices and junior high debaters on her team. She’s super excited to be working with PepTalk this year!",
		region : "Midwest",
	},
     {
		path : "assets/css/images/Kirtan.png",
		personTitle : "Kirtan Patel, McDowell (PA)",
		description : "Kirtan Patel is a senior at McDowell High School in Erie Pennsylvania. Kirtan competes on both the PA traditional circuit and the northeast TOC bid circuit. As a junior he won the Pennsylvania state tournament and broke to double octos of the NCFL national tournament specializing in judge adaptation and argument generation. On the progressive circuit he went to numerous bid tournaments specializing in high theory kritiks specifically baudrillard and agamben. He is excited to work with PepTalk this year!",
		region : "Northeast",
	},
    
    {
		path : "assets/css/images/Curtis.png",
		personTitle : "Curtis Chang, Scarsdale (NY)",
		description : "Curtis is a junior in Scarsdale High School, serving as a team officer in his third year of debate. As a sophomore, he broke at tournaments such as Blake, Princeton, and Apple Valley, and reached the bid round at the Harvard Invitational. He is primarily interested in theory/topicality and philosophy, and is excited to work with PepTalk this year!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/PepTalk.jpg",
		personTitle : "Nevin Gera, McMillen (TX)",
		description : "bio coming soon!",
		region : "Texas",
	},
    {
		path : "assets/css/images/PepTalk.jpg",
		personTitle : "Christine Wang, Lexington (MA)",
		description : "bio coming soon!",
		region : "Northeast",
	},
    {
		path : "assets/css/images/Arjan.jpg",
		personTitle : "Arjan Kang, King (FL)",
		description : "Arjan Kang is a senior at King High School. He is currently entering his fourth year of debate as his school’s LD captain. He has broken at multiple national tournaments and received a bid to the tournament of champions. His debate interests include philosophy, theory, and some kritiks. He is excited to work with PepTalk this year!",
		region : "Southeast",
	},
    {
		path : "assets/css/images/PepTalk.jpg",
		personTitle : "David Herrera, Strake Jesuit (TX)",
		description : "bio coming soon!",
		region : "Texas",
	},
    {
		path : "assets/css/images/PepTalk.jpg",
		personTitle : "David Herrera, Strake Jesuit (TX)",
		description : "bio coming soon!",
		region : "Texas",
	},
    {
		path : "assets/css/images/Madi.png",
		personTitle : "Madi Crowley, Lake Highland (FL)",
		description : "Madi Crowley is a senior from Lake Highland Preparatory School and this is her 5th year debating. Madi has consistently competed on the national circuit, including reaching a bid round at Blue Key and semis at Florida States. She enjoys reading kritikal literature like dean and weheliye but also loves reading tricks.",
		region : "Southeast",
	},
    {
		path : "assets/css/images/Adnan.jpg",
		personTitle : "Adnan Fatakdawala, The Village (TX)",
		description : "Adnan is a senior and President of the Speech and Debate team at The Village School and is entering his 4th year of debate. He has reached out rounds at tournaments such as TFA state, University of Texas Longhorn Classic, and Colleyville. His debate interests include policy arguments, T/theory, and anti-blackness.",
		region : "Texas",
	},
]

const master_admins = [
	{
		path : "assets/css/images/Animesh.jpg",
		personTitle : "Animesh Joshi",
		description : "Animesh Joshi is a senior at WDM Valley High School and has eight career bids, going to the Tournament of Champions three times. After working with PepTalk the last two years, he is looking forward to running the program as co-president and acting as web developer! He's championed the Yale Invitational, Florida Blue Key, and the Iowa State Tournament (in PF!), while also reaching elimination rounds at Bronx, Apple Valley, the Glebrooks, Blake, Lexington, and Harvard. His debate interests include analytical philosophy, theory, and the occasional trick. He's very excited to continue mentoring this year!",
		region : "Texas",
        link : "https://www.facebook.com/animesh.joshi33690",
	},
	{
		path : "assets/css/images/Evan.jpg",
		personTitle : "Evan Li",
		description : "Evan is a senior at Lexington High School in Massachusetts, going into his 4th year of debate. After working with PepTalk last year, he is looking forward to running the program as a co-president! His debate interests include theory and identity Kritiks, but he is open to teaching all kinds of debate. Thus far, Evan has received 5 bids to the Tournament of Champions and has championed various tournaments, including the Newark Invitational, Harrison Round Robin, and Massachusetts State Tournament while also reaching elimination rounds of Harvard, Princeton, UPenn, and Mid American Cup. His teaching experience includes tutoring multiple students at his high school and working at various debate camps for middle schoolers.",
		region : "Northeast",
        link : "https://www.facebook.com/evan.li.50767",

	},
	{
		path : "assets/css/images/Perry.jpg",
		personTitle : "Perry Beckett",
		description : "Perry is a senior at American Heritage in Plantation Florida who is in his fourth year of debate. After working with PepTalk last year, he is looking forward to helping run the program as vice president! He has reached multiple bid rounds at large national tournaments, and is the captain of his school’s LD team. Some of his debate interests include Tricks, Framework debate, and Theory.",
		region : "Southeast",
        link : "https://facebook.com/PerryBeckett02",

	}
];